alphagov/verify-utils-libs

- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/DeserializablePublicKeyConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/DeserializablePublicKeyConfigurationDeserializer.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/EncodedCertificateConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/EncodedPrivateKeyConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/PrivateKeyConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/PrivateKeyConfigurationDeserializer.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/PrivateKeyFileConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/PublicKeyFileConfiguration.java
- security-utils/src/main/java/uk/gov/ida/common/shared/configuration/PublicKeyFileConfigurationDeserializer.java
- security-utils/src/test/java/uk/gov/ida/common/shared/configuration/EncodedCertificateConfigurationTest.java
- security-utils/src/test/java/uk/gov/ida/common/shared/configuration/EncodedPrivateKeyConfigurationTest.java
- security-utils/src/test/java/uk/gov/ida/common/shared/configuration/PrivateKeyFileConfigurationTest.java
As part of the upgrade, jackson has upgraded to 2.8.
They over-eagerly prevent our polymorphism (https://github.com/FasterXML/jackson-databind/issues/1358)
I removed the defaultImpl in the last commit but actually that would cause a lot of extra work.
I believe the best solution for now is to use custom deserialisers for the interfaces.
Tested by running msa and stubs with this change locally.
Solo: hugh-emerson
> TT-1211: upgrading dropwizard

- security-utils/src/test/java/uk/gov/ida/common/shared/security/verification/CertificateChainValidatorTest.java
The recent Java security update slightly changed the way in which cert
validation errors are reported.
We have now updated the test to reflect this.
The error message is now more generic, but the 'reason' still specifies
that the failure is due to an expired cert.
Authors: @michaelwalker, @mahmudh
> BAU: Fix failing expired cert validation test.

- security-utils/src/test/java/uk/gov/ida/common/shared/security/verification/CertificateChainValidatorTest.java
There seems to be some difference in the exception messages thrown by
the certificate timestamp checker depending on the system. It's probably
to do with the version of java. The test is probably too strict (do we
actually care about the exact exception message thrown?), but this at
least means the test will pass consistently so nobody else will have to
waste time tracking down the failure.
Authors: @richardtowers
> bau: Loosen test that was failing on some machines but not Jenkins

- rest-utils/build.gradle
Latest version of event emitter library enables clients to send encrypted events to stub SQS or real SQS.
Authors: @adityapahuja
> ABD-35: Update to use latest version of event emitter lib

- .travis.yml
- README.md
- build.gradle
- rest-utils/build.gradle
I've had to upgrade dropwizard-logstash quite a long way here (1.1.4-49 to 1.2.2-67) because it wasn't being published to bintray properly.
Otherwise just doing the same environment variable feature flag to use the public binaries instead of the ones on artifactory, and setting up travis.
> bau: Build on travis

- common-utils/build.gradle
- rest-utils/build.gradle
- security-utils/build.gradle
Upgrade Dropwizard to 1.3.5 to fix various security issues.
Authors: @adityapahuja
> 49: Upgrade Dropwizard to 1.3.5

- rest-utils/build.gradle
- rest-utils/src/main/java/uk/gov/ida/configuration/JerseyClientWithRetryBackoffConfiguration.java
- rest-utils/src/main/java/uk/gov/ida/restclient/ClientProvider.java
- rest-utils/src/main/java/uk/gov/ida/restclient/TimeoutRequestRetryWithBackoffHandler.java
- rest-utils/src/test/java/uk/gov/ida/restclient/RestClientTimeoutTest.java
- rest-utils/src/test/java/uk/gov/ida/restclient/TestApplication.java
- rest-utils/src/test/java/uk/gov/ida/restclient/TestApplicationConfig.java
- rest-utils/src/test/java/uk/gov/ida/restclient/TimeoutRequestRetryHandlerTest.java
- rest-utils/src/test/java/uk/gov/ida/restclient/TimeoutRequestRetryWithBackoffHandlerTest.java
Create new retry handler that introduces a backoff before retry
Create an extended JerseyClientConfig with backoff parameters included
Update ClientProvider to use appropriate retry handler based on passed parameters
Co-authored-by: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
> HUB-142: Add MSA Retries with Back-off

- rest-utils/src/main/java/uk/gov/ida/jerseyclient/JerseyClientWithRetryBackoffHandlerConfigurationBuilder.java
Correct return type on JerseyClientWithRetryBackoffHandlerConfigurationBuilder.build()
> HUB-142: Allow MSA to retry

- common-utils/build.gradle
- common-utils/src/main/java/uk/gov/ida/shared/utils/AllowUnknownPropertiesConfigurationFactoryFactory.java
- Dropwizard-guicier version >1.0 contain a class
that stops Dropwizard's attempts to disabled the
AllowUnknownProperties behavious on the global ObjectMapper
(at least during configuration file deserialization)
- As we move away from Guice, it would be nice to be able to
implement this behaviour
- By adding this factory in the Dropwizard bootstrap we will
be able to explicitly allow this behaviour instead of relying
on dropwizard-guicier doing it magically
> BAU: Add unknown property object mapper helper

- rest-utils/build.gradle
Update libraries to include new values for EventDetailsKey enum.
Co-authored-by: Chris Clayson <chris.clayson@digital.cabinet-office.gov.uk>
> HUB-380 update libraries

- common-utils/build.gradle
- rest-utils/build.gradle
- security-utils/build.gradle
> BAU Bump bintray plugin to 1.8.4

- common-utils/build.gradle
- rest-utils/build.gradle
- security-utils/build.gradle
The `dropwizard-configuration`, `dropwizard-configuration` and
`dropwizard-core` dependencies all had a transitive dependencies on
`jackson-databind@2.9.6`. This version of jackson-databind is vulnerable
to CVE-2018-19361, CVE-2018-19360, CVE-2018-19362, CVE-2018-14721,
CVE-2018-14719, CVE-2018-14720 and CVE-2018-14718.
Bumping these deps also fixes an issue with a transitive dependency,
`jackson-datatype-jsr310`, that can allow a DoS attack.
> BAU Bump dependency versions to mitigate security issues

- security-utils/build.gradle
- security-utils/src/main/java/uk/gov/ida/common/shared/security/TrustStoreMetrics.java
This adds a TrustStoreMetrics class for outputting certificate expiry
dates as Prometheus metrics.  This should make it more visible what
certificates actually exist in a trust store, and when they expire.
An example of how you might use this (in SamlProxyApplication):
@Override
public void run(SamlProxyConfiguration configuration, Environment environment) throws Exception {
// ...
MetadataResolverConfiguration metadataConfiguration = configuration.getMetadataConfiguration();
TrustStoreMetrics trustStoreMetrics = new TrustStoreMetrics();
metadataConfiguration.getHubTrustStore().ifPresent(hubTrustStore -> trustStoreMetrics.registerTrustStore("hub", hubTrustStore));
metadataConfiguration.getIdpTrustStore().ifPresent(idpTrustStore -> trustStoreMetrics.registerTrustStore("idp", …
> Add TrustStoreMetrics class

- .travis.yml
- build.gradle
- common-utils/build.gradle
- rest-utils/build.gradle
- rest-utils/src/main/java/uk/gov/ida/resources/VersionInfoResource.java
- rest-utils/src/test/java/uk/gov/ida/jerseyclient/ErrorHandlingClientTest.java
- security-utils/build.gradle
- Mockito needed bumping which broke some tests which were using a checked Exception.
- `jaxb-api` was removed in JDK9 and needs importing explicitly if you want to use it.
- Java's class loading strategy changed in Java9 so we had to change the class loader used. [See here for a better explanation](https://blog.codefx.org/java/java-11-migration-guide/#Casting-To-URL-Class-Loader).
> EID-1448: Upgrade to java 11

- build.gradle
Previously when the build was run on the ci-1 box it was published to a
folder on that box called `/srv/maven`. This folder was synced with
artifactory and the published package would end up it the whitelisted
repos.
We're moving to build this library on concourse where we don't have any
magic folders, so we should publish directly to artifactory.
> EID-1469 Publish directly to artifactory

- build.gradle
This updates the publishing URL to match other libraries. This allows
the artifact to be PUT and is available in the whitelisted repos.
> EID-1469 Update publishing URL

- build.gradle
Previously the package was just published to a directory on the jenkins
box and needed no creds. Now it's pushing to a remote it does.
> EID-1469 Add creds to publishing repo config

- .travis.yml
- build.gradle
Ensure that the build will break if Java 9+ features are used. There are still some consumers of the library who have not yet finished migrating to Java 11, alas.
Ideally, we should be able to revert this change in a few months time.
> BAU: enforce back-compatibility with Java 8

- common-utils/build.gradle
- rest-utils/build.gradle
- security-utils/build.gradle
A few vulnerabilities were found in 1.3.9 which were affecting downstream
projects (hub).
[CVE-2019-10247](https://snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-174560)
[CVE-2019-12086](https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-174736)
> BAU Upgrade dropwizard to 1.3.12

- rest-utils/build.gradle
- Includes SQS changes for DCS.
Co-authored-by: Alex Wilson <alex.wilson@digital.cabinet-office.gov.uk>
> OGD-138: Upgrade Event Emitter library version.

- rest-utils/build.gradle
- Bring in EventEmitterSQS refactoring: https://github.com/alphagov/verify-event-emitter/pull/37
Co-authored-by: Alex Wilson <alex.wilson@digital.cabinet-office.gov.uk>
> OGD-138: Refactor Event SQS Module

- rest-utils/src/main/java/uk/gov/ida/truststore/ClientTrustStoreConfiguration.java
Add a flag for marking `ClientTrustStoreConfiguration` enabled \ disabled.
This is a feature flag for removing the requirement to validate RP certificates
in the client microservices. Certificate validation will be done on the
Config microservice when required.
co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov>
> MKaGPO9X: Add enabled flag to TrustStore Config

- rest-utils/src/main/java/uk/gov/ida/bundles/LoggingBundle.java
We want to ensure that the filter that clears the MDC is run last. This is so that previous filters can write log messages with the diagnostic context still set.
Thus, this filter must be matched early. Filters that run first run their post-request clean-up last, which is what we want here
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
> OGD-228: Ensure MDC is cleared last

- .travis.yml
Travis's default distribution, 'Xenial', no longer supports testing with oraclejdk8. The options are to use and old distribution, `trusty`, or drop testing with oraclejdk8.
Since `verify-saml-libs` has already been updated to drop oraclejdk8, that is what we will do here.
> BAU: Stop travis testing with oraclejdk8

- .gitignore
Ignore `common-utils/out/` and `rest-utils/out/`. These contain build artifacts that should not be added to git.
> BAU: Ignore `out` directories.

- .travis.yml
- rest-utils/src/main/java/uk/gov/ida/jerseyclient/ErrorHandlingClient.java
- rest-utils/src/main/java/uk/gov/ida/jerseyclient/JsonClient.java
- rest-utils/src/test/java/uk/gov/ida/jerseyclient/ErrorHandlingClientTest.java
- rest-utils/src/test/java/uk/gov/ida/jerseyclient/JsonClientTest.java
We want to use the Json client in the proxy-node to get a resource from
a new micro services. We need to be able to pass Istio headers along
with the GET request. This PR extends the `ErrorHandlingClient` to accept
a map of headers to include, without also including any cookies.
> EID-1833: Add get with headers to Json client

- rest-utils/build.gradle
Dropwizard 2.0.2 was causing issues in the proxy node.
Version 1.3.20 we stop this. No reason for using 2.0.+
> BAU: fix dropwizard version

- .github/dependabot.yml
- .travis.yml
- README.md
- build.gradle
- Enable dependabot for verify-utils-libs
- Remove codacy as it has been removed from other verify projects and is not used
> BAU - Enable dependabot for verify-utils-libs

- .sdkmanrc
- build.gradle
- common-utils/build.gradle
- rest-utils/build.gradle
- security-utils/build.gradle
This sets the dependency of interest to:
````
❯ ./gradlew allDeps | grep "commons-text" | sort | uniq
\--- org.apache.commons:commons-text:1.10.0
|    \--- org.apache.commons:commons-text:1.10.0
|    |    \--- org.apache.commons:commons-text:1.10.0
````
> BAU build: bump to latest dropwizard version
